config/routes.rb
Rails.application.routes.draw do
  root 'employees#index'

  resources :tasks, :employees, :particulars, :bills, :users
  resources :account_activations, only: [:edit]

  get '/signup', to: 'users#new', as: :signup
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'employee/task/:id', to: 'employees#employee_tasks'
  get 'employee/task/new/:id', to: 'employees#employee_new_task'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :tasks, inverse_of: :employee

  accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  def employee_tasks
    @employee = Employee.find(params[:id])
    @tasks = @employee.tasks
  end

  def employee_new_task
    @employee = Employee.find(params[:id])
    # TODO : model
    @bills = Bill.where(is_complete: false)
    @employee.tasks.build
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :emp_type, :address, :contact, :id, tasks_attributes: [:date, :bill_no, :task_particular, :quantity, :total, :_destroy])
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= simple_form_for(@employee) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="row form-data-margin">
    <%= f.label :name, class: "col-3 m-0 p-0" %>
    <%= f.text_field :name, class: "col-6 form-control"%>
  </div>

  <div class="row form-data-margin">
    <%= f.label :type, class: "col-3 m-0 p-0" %>
    <%= f.text_field :emp_type, class: "col-6 form-control" %>
  </div>

  <div class="row form-data-margin">
    <%= f.label :address, class: "col-3 m-0 p-0" %>
    <%= f.text_field :address, class: "col-6 form-control" %>
  </div>

  <div class="row form-data-margin">
    <%= f.label :contact, class: "col-3 m-0 p-0" %>
    <%= f.text_field :contact, class: "col-6 form-control" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success btn-sm"%>
  </div>
<% end %>

app/views/employees/_task_fields.html.erb
<div class='nested-fields'>
  <div class = "card alert-success">
    <div class= "card-body">
      <%= link_to_remove_association '<i class="btn btn-danger fas fa-times float-right p-1"></i>'.html_safe, f %>
      <div class="row">
        <div class="col-5">
          <%= f.label :bill_no %>
          <select class="form-control" name="bill_no" id="task_bill_no">
            <%= @bills.each do |bill| %>
              <option><%= bill.bill_no %></option>
            <% end %>
          </select>
        </div>

        <div class="col-7">
          <%= f.label :date %>
          <%= f.input :date, id: "datepicker", label: false, class: "form-control"  %>
        </div>
      </div>
      <div class="row">
        <div class="col-6">
          <%= f.label :particular %>
          <%= f.text_field :task_particular, class: "form-control" %>
        </div>

        <div class="col-6">
          <%= f.label :quantity %>
          <%= f.text_field :quantity, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/edit.html.erb
<div class="container">
  <div class="row">
    <div class= "col col-md-6 offset-md-3 col-sm-10 offset-sm-1">
      <div class="login">
        <div class="row">
          <h1 class="col-10 form_header">Edit Employee</h1>
          <%= link_to 'Show', @employee, class: "col-2", class: "btn btn-primary btn-sm" %>
        </div>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= render 'form', employee: @employee %>
    </div>
  </div>
  </div>
</div>

app/views/employees/employee_new_task.html.erb
<%= simple_form_for @employee, local: true, html: { class: 'form' } do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="row">
      <div class= "col col-md-6 offset-md-3 col-sm-10 offset-sm-1">
        <div class="login">
          <h1 class="form_header">New Task</h1>
          <div id='tasks'>
            <!-- <%= f.simple_fields_for :tasks do |task| %>
              <%= render 'task_fields', :f => task %>
            <% end %> -->
          <div class='links'>
            <%= link_to_add_association 'Add Task', f, :tasks, class: "btn btn-primary btn-sm margin-top-btm-8" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="actions">
  <%= f.submit %>
</div>
    </div>
  </div>
<% end %>

app/views/employees/employee_tasks.html.erb
<p id="notice"><%= notice %></p>

<h1>Work Record</h1>
<h3> <%= @employee.name %> </h3>
<div class="task-table">
    <div class="container-fluid">
      <div class="row">
        <div class="table-responsive">
          <table class="table text-center">
            <thead class="grey-lighten-5">
              <tr>
                <th scope="col">Date</th>
                <th scope="col">Bill no</th>
                <th scope="col">Task particular</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total</th>
                <th scope="col" colspan="3">
                  <div class = "float-right">
                      <%= link_to '<button class = "btn btn-success btn-sm" type="button">Add Task <i class="fas fa-user-plus"></i></button>'.html_safe, "/employee/task/new/#{@employee.id}" %>
                  </div>
                </th>
              </tr>
            </thead>
            <tbody>
              <% @tasks.each do |task| %>
                <tr>
                  <td><%= task.date %></td>
                  <td><%= task.bill_no %></td>
                  <td><%= task.task_particular %></td>
                  <td><%= task.quantity %></td>
                  <td><%= task.total %></td>
                  <td><%= link_to 'Show', task %></td>
                  <td><%= link_to 'Edit', edit_task_path(task) %></td>
                  <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
              </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>
<div class="parallax-container">
  <div class="parallax">
    <%=image_tag("back.jpg")%>
  </div>
</div>

<div class="section white">
  <div class="row container">
    <div>
      <h1>Employees</h1>
      <div class="container-fluid">
        <div class="row">
          <div class="table-responsive table-striped emp-table">
            <table class="table text-center">
              <thead class = "gradient">
                <tr>
                  <th scope="col">Name</th>
                  <th scope="col">Type</th>
                  <th scope="col">Address</th>
                  <th scope="col">Contact</th>
                  <th>
                    <div class = "float-right">
                        <%= link_to '<button class = "btn btn-success btn-sm" type="button">Add Employee <i class="fas fa-user-plus"></i></button>'.html_safe, new_employee_path %>
                    </div>
                  </th>
                </tr>
              </thead>
                <tbody >
                  <% @employees.each do |employee| %>
                    <tr>
                      <td><%= link_to "#{employee.name}", "/employee/task/#{employee.id}"%></td>
                      <td><%= employee.emp_type %></td>
                      <td><%= employee.address %></td>
                      <td><%= employee.contact %></td>
                      <td>
                        <%= link_to 'Show', employee %>
                        <%= link_to 'Edit', edit_employee_path(employee) %>
                        <%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
            </table>
          </div>
        </div>
        </div>
      </div>
    <p class="grey-text text-darken-3 lighten-3">Parallax is an effect where the background content or image in this case, is moved at a different speed than the foreground content while scrolling.</p>
  </div>
</div>

<div class="parallax-container">
  <div class="parallax">
    <%=image_tag("back.jpg")%>
  </div>
</div>

app/views/employees/new.html.erb
<div  class = "gradient">
  <div class="container">
    <div class="row">
      <div class= "col col-md-6 offset-md-3 col-sm-10 offset-sm-1">
        <div class="login">
        <h1 class="form_header">Add New Employee</h1>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <%= render 'form', employee: @employee %>
      </div>
    </div>
    </div>
  </div>

</div>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @employee.emp_type %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee.address %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @employee.contact %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>