config/routes.rb
Rails.application.routes.draw do
  root 'employees#index'

  resources :tasks, :employees, :particulars, :bills, :users
  resources :account_activations, only: [:edit]

  get '/signup', to: 'users#new', as: :signup
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'employee/task/:id', to: 'employees#employee_tasks'
  get 'employee/task/new/:id', to: 'employees#employee_new_task'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bill.rb
class Bill < ApplicationRecord
  has_many :particulars, inverse_of: :bill
  accepts_nested_attributes_for :particulars, reject_if: :all_blank, allow_destroy: true
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
    @bill.particulars.build
  end

  # GET /bills/1/edit
  def edit
    @bill.particulars.build
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)
    @bill.grand_total = @bill.total - @bill.advance
    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:bill_no, :total, :advance, :grand_total, :is_complete, particulars_attributes: [:id, :name, :quantity, :_destroy])
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<%= simple_form_for @bill, local: true, html: { class: 'form' } do |f| %>
  <% if bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "card grey-lighten-5 ">
    <div class= "card-body row form-data-margin">
      <div class="row form-data-margin">
        <%= f.label :bill_no %>
        <%= f.text_field :bill_no, class: "form-control" %>
      </div>

      <div class="row form-data-margin">
        <%= f.label :is_complete %>
        <%= f.check_box :is_complete, class: "form-control" %>
      </div>
  </div>

  <div>

      <h1 class="form_header">Particulars</h1>
      <div class="card grey-lighten-5">
        <div class = "card-body row form-data-margin" id='particulars'>
          <%= f.simple_fields_for :particulars do |particular| %>
            <%= render 'particular_fields', :f => particular %>
          <% end %>
        </div>
          <div class='links'>
            <%= link_to_add_association 'Add Particular', f, :particulars, partial: 'particular_fields', class: "btn btn-primary btn-sm margin-top-btm-8" %>
          </div>
      </div>

    <div class = "card grey-lighten-5">
      <div class= "card-body row form-data-margin">
        <div class="col-4">
          <%= f.label :total %>
          <%= f.text_field :total, class: "form-control" %>
        </div>

        <div class="col-4">
          <%= f.label :advance %>
          <%= f.text_field :advance, class: "form-control" %>
        </div>

        <div class="col-4">
          <%= f.label :grand_total%>
          <%= f.text_field :grand_total, class: "form-control", disabled: true %>
        </div>
      </div>
    </div>
    <div class="actions">
      <%= f.submit class: "btn btn-success btn-sm"%>
    </div>
  </div>
</div>
<% end %>

app/views/bills/_particular_fields.html.erb
<div class='nested-fields'>
  <div class = "card alert-success">
    <div class= "card-body">
      <%= link_to_remove_association '<i class="btn btn-danger fas fa-times float-right p-1"></i>'.html_safe, f %>
      <div class="row">
        <div class="col-6">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="col-6">
          <%= f.label :quantity %>
          <%= f.text_field :quantity, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>
<div class="">
  <h1>Bills</h1>
  <div class="container-fluid">
    <div class="row">
      <div class="table-responsive table-striped emp-table">
        <table class="table text-center">
          <thead class="grey-lighten-5">
            <tr>
              <th scope="col">Bill no</th>
              <th scope="col">Total</th>
              <th scope="col">Advance</th>
              <th scope="col">Grand total</th>
              <th scope="col">Is complete</th>
              <th scope="col">
                <div class = "float-right">
                    <%= link_to '<button class = "btn btn-success btn-sm" type="button">Add Bill <i class="fas fa-user-plus"></i></button>'.html_safe, new_bill_path %>
                </div>
              </th>
            </tr>
          </thead>
            <tbody>
              <% @bills.each do |bill| %>
                <% if bill.is_complete %>
                <tr class = "light-blue">
                <% else %>
                  <tr>
                <% end %>
                  <td><%= bill.bill_no %></td>
                  <td><%= bill.total %></td>
                  <td><%= bill.advance %></td>
                  <td><%= bill.grand_total %></td>
                  <td><%= bill.is_complete %></td>
                  <td>
                    <%= link_to 'Show', bill %>
                    <%= link_to 'Edit', edit_bill_path(bill) %>
                    <%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

<%= link_to 'New Bill', new_bill_path %>

app/views/bills/new.html.erb
<div class="container">
  <div class="row">
    <div class= "col col-md-8 offset-md-2 col-sm-10 offset-sm-1">
      <div class="login">
      <h1 class="form_header">Add New Bill</h1>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= render 'form', bill: @bill %>
    </div>
  </div>

  </div>

</div>


<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class= "col col-md-6 offset-md-3 col-sm-10 offset-sm-1">
      <div class="login">
        <h1 class="form_header">
          <strong>Bill no:</strong>
          <%= @bill.bill_no %>
        </h1>

        <table class = "table">
          <tr>
            <th> Particulars </th>
            <th> Quantity </th>
          </tr>
          <tr>
            <% @bill.particulars.each do |particular| %>
            <td> <%= particular.name %> </td>
            <td> <%= particular.quantity %> </td>
          </tr>
          <% end %>
        </table>

        <div class="float-right">
          <p>
            <strong>Total:</strong>
            <%= @bill.total %>
          </p>

          <p>
            <strong>Advance:</strong>
            <%= @bill.advance %>
          </p>

          <p>
            <strong>Grand total:</strong>
            <%= @bill.grand_total %>
          </p>

          <p>
            <strong>Is complete:</strong>
            <%= @bill.is_complete %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>