config/routes.rb
Rails.application.routes.draw do
  root 'employees#index'

  resources :tasks, :employees, :particulars, :bills, :users
  resources :account_activations, only: [:edit]

  get '/signup', to: 'users#new', as: :signup
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'employee/task/:id', to: 'employees#employee_tasks'
  get 'employee/task/new/:id', to: 'employees#employee_new_task'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/particular.rb
class Particular < ApplicationRecord
  belongs_to :bill
end

app/controllers/particulars_controller.rb
class ParticularsController < ApplicationController
  before_action :set_particular, only: [:show, :edit, :update, :destroy]

  # GET /particulars
  # GET /particulars.json
  def index
    @particulars = Particular.all
  end

  # GET /particulars/1
  # GET /particulars/1.json
  def show
  end

  # GET /particulars/new
  def new
    @particular = Particular.new
  end

  # GET /particulars/1/edit
  def edit
  end

  # POST /particulars
  # POST /particulars.json
  def create
    @particular = Particular.new(particular_params)

    respond_to do |format|
      if @particular.save
        format.html { redirect_to @particular, notice: 'Particular was successfully created.' }
        format.json { render :show, status: :created, location: @particular }
      else
        format.html { render :new }
        format.json { render json: @particular.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /particulars/1
  # PATCH/PUT /particulars/1.json
  def update
    respond_to do |format|
      if @particular.update(particular_params)
        format.html { redirect_to @particular, notice: 'Particular was successfully updated.' }
        format.json { render :show, status: :ok, location: @particular }
      else
        format.html { render :edit }
        format.json { render json: @particular.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /particulars/1
  # DELETE /particulars/1.json
  def destroy
    @particular.destroy
    respond_to do |format|
      format.html { redirect_to particulars_url, notice: 'Particular was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_particular
      @particular = Particular.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def particular_params
      params.require(:particular).permit(:name, :cus_rate, :emp_rate)
    end
end

app/helpers/particulars_helper.rb
module ParticularsHelper
end

app/views/particulars/_form.html.erb
<%= form_with(model: particular, local: true) do |form| %>
  <% if particular.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(particular.errors.count, "error") %> prohibited this particular from being saved:</h2>

      <ul>
      <% particular.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :cus_rate %>
    <%= form.text_field :cus_rate %>
  </div>

  <div class="field">
    <%= form.label :emp_rate %>
    <%= form.number_field :emp_rate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/particulars/edit.html.erb
<h1>Editing Particular</h1>

<%= render 'form', particular: @particular %>

<%= link_to 'Show', @particular %> |
<%= link_to 'Back', particulars_path %>

app/views/particulars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Particulars</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cus rate</th>
      <th>Emp rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @particulars.each do |particular| %>
      <tr>
        <td><%= particular.name %></td>
        <td><%= particular.cus_rate %></td>
        <td><%= particular.emp_rate %></td>
        <td><%= link_to 'Show', particular %></td>
        <td><%= link_to 'Edit', edit_particular_path(particular) %></td>
        <td><%= link_to 'Destroy', particular, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Particular', new_particular_path %>

app/views/particulars/new.html.erb
<h1>New Particular</h1>

<%= render 'form', particular: @particular %>

<%= link_to 'Back', particulars_path %>

app/views/particulars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @particular.name %>
</p>

<p>
  <strong>Cus rate:</strong>
  <%= @particular.cus_rate %>
</p>

<p>
  <strong>Emp rate:</strong>
  <%= @particular.emp_rate %>
</p>

<%= link_to 'Edit', edit_particular_path(@particular) %> |
<%= link_to 'Back', particulars_path %>