config/routes.rb
Rails.application.routes.draw do
  root 'employees#index'

  resources :tasks, :employees, :particulars, :bills, :users
  resources :account_activations, only: [:edit]

  get '/signup', to: 'users#new', as: :signup
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'employee/task/:id', to: 'employees#employee_tasks'
  get 'employee/task/new/:id', to: 'employees#employee_new_task'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_notice.html.erb
<% if notice %>
    <div class = "flash">
    <p class="alert alert-success"><%= notice %></p>
  </div>
<% end %>

app/views/layouts/_top_navigation.html.erb
<!-- <nav class="navbar navbar-expand-lg nav-bar">
    <div class="container-fluid">
      <a class="navbar-brand text-white" href="/">
        <%=image_tag("logo.png", class: "logo")%>
        New Fashion Tailors
      </a>
    </div>
    <ul class = "nav navbar-nav w-75 justify-content-end">
        <% if logged_in? %>
        <li class = "nav-item selector"><%= link_to 'Employees <i class="fas fa-save"></i>'.html_safe, employees_path, :class => 'nav-link text-white'%></li>
        <li class = "nav-item"><%= link_to 'Bills <i class="fas fa-save"></i>'.html_safe, bills_path, :class => 'nav-link text-white'%></li>
          <li class = "nav-item"><%= link_to "Users", users_path, :class => 'nav-link text-white' %></li>
          <li class = "nav-item dropdown">
            <a href = "#" class = "dropdown-toggle nav-link text-white" data-toggle = "dropdown">
              Account <b class = "caret"></b>
            </a>
            <ul class = "dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class = "divider"></li>
              <li> <%= link_to "Log out", logout_path, method: :delete %> </li>
            </ul>
          </li>
        <% else %>
          <li> <%= link_to "Log in", login_path, :class => 'nav-link text-white' %></li>
        <% end %>
    </ul>
</nav> -->
<ul id="account-dropdown" class="dropdown-content">
  <li><%= link_to "Profile", current_user %></li>
  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
  <li class = "divider"></li>
  <li> <%= link_to "Log out", logout_path, method: :delete %> </li>
</ul>

<nav>
  <div class="nav-wrapper">
    <a class="brand-logo" href="/">
      <%=image_tag("logo.png", class: "logo")%>
      New Fashion Tailors
    </a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if logged_in? %>
      <li class = "selector"><%= link_to 'Employees'.html_safe, employees_path, :class => 'nav-link text-white'%></li>
      <li class = ""><%= link_to 'Bills'.html_safe, bills_path, :class => 'nav-link text-white'%></li>
        <li class = ""><%= link_to "Users", users_path, :class => 'nav-link text-white' %></li>
        <li><a class="dropdown-trigger" data-target="account-dropdown">Account<i class="material-icons right">arrow_drop_down</i></a></li>
      <% else %>
        <li> <%= link_to "Log in", login_path, :class => 'nav-link text-white' %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FashionApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/top_navigation" %>
    <%= render "layouts/flash_notice" %>
    <%= yield %>
    <div class="debug_dump">
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>

  <script>

</script>
</html>